### ISSUE TITLE
undefined method job_id

### ISSUE THREAD

**Issue by six7zero9** [ondrejbartas/sidekiq-cron#107]
I have a simple worker that takes no arguments which I am trying to run every minute in testing but I am getting this error:

`NoMethodError: undefined method `job_id=' for #<ExampleWorker:xxxxxxxxx>`

**Comment by ondrejbartas** [comment]
Hi,

pls paste your worker code into this discusion pls. Most probably you are not including Sidekiq::Worker

**Comment by six7zero9** [comment]
config/initializers/sidekiq.rb
```
Sidekiq.configure_server do |config|
  schedule_file = "config/sidekiq_schedule.yml"

  if File.exists?(schedule_file) && Sidekiq.server?
    Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file)
  end
end
```

config/sidekiq_schedule.yml

```
schedule_example_job:
  name: "example_job"
  cron: "*/1 * * * *"
  class: "ExampleWorker"
  queue: default
  active_job: true

```

app/workers/example_worker.rb

```
class ExampleWorker
  include Sidekiq::Worker

  def perform
    # Calls another sidekiq worker to perform_async()   
  end
end

```

This is what I have currently. I wasn't running into anything weird while just manually firing the worker off from terminal with something like 

`ExampleWorker.new.perform`]

which gathers a list and calls perform_async inside a  `foo.each do |bar|` wrapper.
