### ISSUE TITLE
Disable a Job on Startup

### ISSUE THREAD

**Issue by mastermindg** [ondrejbartas/sidekiq-cron#136]
I have a job that I use strictly for testing. I don't want it to run ever on it's own. I'm using a yaml loaded from the initializer. Here's my job:

```
schedule_db_cleanup:  
  cron: '* * * * *'
  class: CleanDatabase
  queue: default
  active_job: false
```
How can I add the job without having a schedule or disable it on startup?

**Comment by Linell** [comment]
Try this:

```yml
schedule_db_cleanup:  
  cron: '* * * * *'
  class: CleanDatabase
  queue: default
  active_job: false
  status: "disabled"
```
