### ISSUE TITLE
Starting multiple cron jobs

### ISSUE THREAD

**Issue by henrikholm89** [ondrejbartas/sidekiq-cron#139]
I have trouble starting multiple cron jobs.

Here is my setup:

```
# schedule.yml

match_kickoff_watch_job:
  cron: "*/10 * * * *"
  class: "MatchKickoffWatch"
  queue: match_kickoff_watch
  active_job: true

season_ending_watch_job:
  cron: "18 30 * * *"
  class: "SeasonEndingWatch"
  queue: season_ending_watch
  active_job: true
```

```
# initializers/sidekiq.rb

redis_url = if Rails.env.development?
              "redis://localhost:6379"
            elsif Rails.env.staging?
              begin
                # for staging heroku app
                ENV.fetch("REDISCLOUD_TEAL_URL")
              rescue KeyError
                # for development heroku app
                ENV.fetch("REDISCLOUD_BLUE_URL")
              end
            elsif Rails.env.production?
              ENV.fetch("REDISCLOUD_GREEN_URL")
            end

Sidekiq.configure_server do |config|
  config.redis = { url: redis_url }

  schedule_file = "config/schedule.yml"

  if File.exists?(schedule_file) && Sidekiq.server?
    Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
  end
end

Sidekiq.configure_client do |config|
  config.redis = { url: redis_url }
end
```

This is output I get from rails console `Sidekiq::Cron::Job.all`

![skaermbillede 2017-03-09 15 57 46](https://cloud.githubusercontent.com/assets/8633869/23755607/3ac2d482-04e1-11e7-8754-e7eeb508173a.png)

It also looks from the logs, when I start sidekiq, it only starts the first job in the `schedule.yml`.

![skaermbillede 2017-03-09 15 42 39](https://cloud.githubusercontent.com/assets/8633869/23754948/1b8b294a-04df-11e7-8a0c-f63aeaa80407.png)

Am I doing something wrong here?
