### ISSUE TITLE
Issue on Rails 6 when defining scheduled job in namespace of a Rails model

### ISSUE THREAD

**Issue by sebfie** [ondrejbartas/sidekiq-cron#261]
Hello,

My env : 

1. A model User
2. A worker User::CheckExpiredDrivingLicenceJob

Defining in `schedule.yml` as

```
check_expired_driving_licence_job:
  cron: "0 1 * * *"
  class: "User::CheckExpiredDrivingLicenceJob"
  queue: company_owner_driving_licence
```

After doing `Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)` the model User is overwrite by the module I guess and make `Zeitwerk` fail.

With this overwrite, I got messages like `undefined method email_verified on User`

My solution is to use a namespace Users for my workers
