### ISSUE TITLE
Tasks randomly disappear

### ISSUE THREAD

**Issue by haterecoil** [ondrejbartas/sidekiq-cron#263]
Hello,

first of all thank you very much for this wonderful library. It works pretty well, excepting some randomly disappearing tasks.

I set tasks from the `schedule.yml` file which is correctly read since each `rails console` or `rails server` loads them.
However, from time to time, they disappear!

My setup is a multi-container docker application composed of redis and two images built from my own Dockerfile. One of these two runs `bundle exec  rails server ...` and the other one `bundle exec sidekiq`.

But without any trace in redis nor rails nor sidekiq docker's logs, tasks disappear after a few hours (but no fixed timing). 

I guess it is difficult to debug from few information, but maybe you could have a clue about what could make those disappear. 

What would be the possible reasons?

Here is the `config/schedule.yml` file:
```yaml
fetch_todays_orders_job__07h50:
  cron: "50 7 * * * Europe/Paris" # “At 07:50.”
  class: "FetchTodaysOrdersWorker"
fetch_yesterdays_orders_job__05h50:
  cron: "50 5 * * * Europe/Paris" # “At 05:50.”
  class: "FetchYesterdaysOrdersWorker"
fetch_todays_orders_job__09h50:
  cron: "50 9 * * * Europe/Paris" # “At 09:50.”
  class: "FetchTodaysOrdersWorker"
fetch_todays_orders_job__11h50:
  cron: "50 11 * * * Europe/Paris" # “At 11:50.”
  class: "FetchTodaysOrdersWorker"
fetch_todays_orders_job__13h50:
  cron: "50 13 * * * Europe/Paris" # “At 13:50.”
  class: "FetchTodaysOrdersWorker"
```

and `config/initializers/sidekiq.rb`

```yaml
require 'sidekiq/cli'

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['JOB_WORKER_URL'] }
end

Sidekiq.configure_client do |config|
  config.redis = { url: ENV['JOB_WORKER_URL'] }
end

schedule_file = Rails.root.join('config', 'schedule.yml').to_s
if File.exist?(schedule_file) && Sidekiq.server?
  p "SIDEKIQ CRON / gonna load file #{schedule_file}"
  Sidekiq::Cron::Job.load_from_hash YAML.load_file(schedule_file)
else
  p "SIDEKIQ CRON / CANNOT LOAD FILE"
end
```
