### ISSUE TITLE
Old cron job not deleted when I changed (removed) cron in file sidekiq_schedule.yml

### ISSUE THREAD

**Issue by troniez** [ondrejbartas/sidekiq-cron#267]
The issue is I update the sidekiq_schedule.yml (this file is defined for cron jobs) and just restart sidekiq, but I sill see the old jobs in cron and they was run!. I expect (or assuming about sidekiq-cron) work base which I defined on sidekiq_schedule.yml. But not, many old jobs still in cron and will be run. 

Reproduce: First I have 3 cron job:

```
the_a_job:
  cron: "0 0 * * *"
  class: "TheAJob"
  queue: default

the_b_job:
  cron: "0 0 * * *"
  class: "TheBJob"
  queue: default

the_c_job:
  cron: "0 0 * * *"
  class: "TheCJob"
  queue: default
```

start sidekiq, in the cron tab on sidekiq web, we will see 3 cron

<img width="975" alt="Screen Shot 2019-12-23 at 10 35 58 AM" src="https://user-images.githubusercontent.com/4206695/71334467-f67a5a80-2570-11ea-9367-276020261c28.png">

Then When I comment out one job:

```
the_a_job:
  cron: "0 0 * * *"
  class: "TheAJob"
  queue: default
# the_b_job:
#   cron: "0 0 * * *"
#   class: "TheBJob"
#   queue: default
the_c_job:
  cron: "0 0 * * *"
  class: "TheCJob"
  queue: default
```

The log said after I restart sidekiq:

<img width="759" alt="Screen Shot 2019-12-23 at 10 36 17 AM" src="https://user-images.githubusercontent.com/4206695/71334510-1a3da080-2571-11ea-9b58-33e5d4f779a5.png">

But We will see 3 job on cron:

<img width="975" alt="Screen Shot 2019-12-23 at 10 35 58 AM" src="https://user-images.githubusercontent.com/4206695/71334539-33dee800-2571-11ea-826e-f4f493ac2a15.png">

Any suggestions would be greatly appreciated
