### ISSUE TITLE
Allow jobs that will never fire to appear at /sidekiq/cron

### ISSUE THREAD

**Issue by chongivan** [ondrejbartas/sidekiq-cron#284]
Hello @ondrejbartas,

Thank you for the gem =)

Here's my request:

I have a schedule.yml
```
never_fire_job:
  cron: "0 0 31 2 *" # At 00:00 on 31 Feb. It will never run
  class: "OneWorker"

two_job:
  cron: "0 0 * * *" # everyday at 00:00
  class: "TwoWorker"

```

Notice that **never_fire_job**'s corn will never run, because of of 31 Feb.

But I notice that at http://mydomain.com/sidekiq/cron, **never_fire_job** does not appear.

How can i make the **never_fire_job** appear at http://mydomain.com/sidekiq/cron?
