### ISSUE TITLE
Jobs run half as often as they should

### ISSUE THREAD

**Issue by danarnold** [ondrejbartas/sidekiq-cron#89]
After upgrading sidekiq to > 4.0 and sidekiq-cron to > 0.3.1, all of our scheduled jobs executed at exactly or almost exactly half of the frequency that they should have. For example, a job that runs once per minute would simply run once every two minutes. I'm not sure what the cause of this is, but reverting back to 0.3.1 with sidekiq 3.5.4 fixed it.

**Comment by sqbell** [comment]
We also are missing jobs after upgrade.

**Comment by mbhnyc** [comment]
I'm seeing jobs that are set to run ones a day, like `0 15 * * *` running once an hour.

**Comment by jclusso** [comment]
Any idea on this @ondrejbartas? It's stopping us from upgrading to Sidekiq 4 which has some really big improvements.

**Comment by jclusso** [comment]
Any idea on this @ondrejbartas? It's stopping us from upgrading to Sidekiq 4 which has some really big improvements.

**Comment by jclusso** [comment]
Any idea on this @ondrejbartas? It's stopping us from upgrading to Sidekiq 4 which has some really big improvements.

**Comment by jclusso** [comment]
@ondrejbartas we are still eagerly waiting a response for almost a month on this :(

**Comment by gdeglin** [comment]
Same issue here

**Comment by phyzalis** [comment]
Anything new about that?

**Comment by jclusso** [comment]
@phyzalis I gave up waiting and was looking at https://github.com/moove-it/sidekiq-scheduler but this seems to run 2x of what it should so we're just currently stuck using Sidekiq 3 still :(

**Comment by phyzalis** [comment]
I will have a look thank you. I need to be able to add jobs programmatically and this sidekiq-cron was perfect. I will have a look inside sidekiq-cron source too when I'll have time.
Thanks

**Comment by phyzalis** [comment]
For me the issue comes from RufusScheduler here:

     Rufus::Scheduler::CronLine.new(@cron).previous_time(now)

https://github.com/ondrejbartas/sidekiq-cron/blob/master/lib/sidekiq/cron/job.rb#L443

I will continue to investigate

**Comment by danarnold** [comment]
@phyzalis Can you elaborate on that? I see that RufusScheduler supports extensions to the standard cron format, but it also claims to support standard cron format.

**Comment by phyzalis** [comment]
In fact my issue was my cron format, I was having 6 elements in it instead of 5.
Fixing this it works perfectly

For example to run something every day at 10, I was using:
0 10 * * * *
Which is wrong and run my task every hour at 10 minutes

The right way was : 0 10 * * *

But I don't think this will help you

**Comment by danarnold** [comment]
Yeah, we were using standard 5 element cron.

**Comment by ondrejbartas** [comment]
@danarnold Hi sorry for delay. How can I help you? I am not really sure what is your problem.

**Comment by danarnold** [comment]
That's fine. I'm not sure where you're confused, I described the problem in the my first comment on the issue. Is there anything I can clarify? Essentially, jobs are running 1/2 as often as they should.

**Comment by hderms** [comment]
@danarnold Can you give us the exact versions of the gems you are running? I created a dirt simple gem which just scheduled a job to run every minute and reports the amount of time between each invocation but can't reproduce the issue. Also it would be helpful to get your sidekiq/sidekiq-cron config. 

I wrote this example worker, which although poorly written, provides a reasonable approximation to how often the cron task is running. https://gist.github.com/hderms/bf484c103573f65942f78cff5243d845

**Comment by danarnold** [comment]
This was with sidekiq 4.0.1, sidekiq-cron 0.4.2.

Here's our cron file with the worker names changed (they are all unique in our app, of course):

```
redacted_worker:
  cron: '*/10 * * * *'
  class: 'RedactedWorker'
  queue: low

redacted_worker:
  cron: '*/1 * * * *'
  class: 'RedactedWorker'
  queue: slow

redacted_worker:
  cron: '*/1 * * * *'
  class: 'RedactedWorker'
  queue: slow

redacted_worker:
  cron: '*/1 * * * *'
  class: 'RedactedWorker'
  queue: slow

redacted_worker:
  cron: '*/5 * * * *'
  class: 'RedactedWorker'
  queue: low

redacted_worker:
  cron: '0 * * * *'
  class: 'RedactedWorker'
  queue: slow

redacted_worker:
  cron: '0 0 */1 * *'
  class: 'RedactedWorker'
  queue: slow

redacted_worker:
  cron: '0 */2 * * *'
  class: 'RedactedWorker'
  queue:  slow

redacted_worker:
  cron: '0 */1 * * *'
  class: 'RedactedWorker'
  queue: low

redacted_worker:
  cron: '*/5 * * * *'
  class: 'RedactedWorker'
  queue: low

redacted_worker:
  cron: '*/5 * * * *'
  class: 'RedactedWorker'
  queue: low
```

It's worth mentioning that we run these workers in production on Heroku with multiple sidekiq instances, so Heroku fires up at least one dyno per queue, meaning that you get dyno processes running `sidekiq -q slow`, running `sidekiq -q low`, etc. This doesn't cause issues using the version we're using right now (sidekiq-cron 0.3.1, sidekiq 3.5.4).
